const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const get=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function cartCount(){return get("toylandCart").reduce((a,x)=>a+x.quantity,0)}
function updateCounts(){const c=cartCount(),w=get("toylandWishlist").length;$$("[data-cart-count]").forEach(x=>x.textContent=c);$$("[data-wishlist-count]").forEach(x=>x.textContent=w)}
function toast(msg){let t=$("#toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast";document.body.append(t)}t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function addToCart(id,qty=1){let cart=get("toylandCart"),p=products.find(x=>x.id==id);if(!p||p.stock<1)return toast("This product is out of stock");let item=cart.find(x=>x.id==id);if(item)item.quantity=Math.min(item.quantity+qty,p.stock);else cart.push({id:p.id,name:p.name,price:p.price,image:p.image,quantity:Math.min(qty,p.stock)});set("toylandCart",cart);updateCounts();toast("Added to Cart")}
function toggleWishlist(id){let w=get("toylandWishlist"),i=w.indexOf(id);if(i>-1){w.splice(i,1);toast("Removed from Wishlist")}else{w.push(id);toast("Added to Wishlist")}set("toylandWishlist",w);updateCounts()}
function productCard(p){let wished=get("toylandWishlist").includes(p.id);return `<article class="product-card"><button class="wish" onclick="toggleWishlist(${p.id})" aria-label="Wishlist">${wished?"❤️":"♡"}</button><a class="product-img" href="product.html?id=${p.id}" aria-label="${p.name}"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('image-fallback')"></a><div class="product-body"><div class="badge">${p.category}</div><div class="product-title">${p.name}</div><div class="rating">★ ${p.rating} (${p.reviews} reviews)</div><div><span class="price">${money(p.price)}</span><span class="old">${money(p.oldPrice)}</span><span class="discount">${p.discount}% OFF</span></div><div class="card-actions"><button class="btn btn-primary" onclick="addToCart(${p.id})">Add to Cart</button><a class="btn btn-outline" href="product.html?id=${p.id}">View</a></div></div></article>`}
function renderProducts(target,list){let el=$(target);if(el)el.innerHTML=list.length?list.map(productCard).join(""):`<div class="empty">No products found.</div>`}
function header(){return `<div class="topbar">Free Delivery on Orders Above ₹999</div><header class="header"><div class="container nav"><a class="logo" href="index.html">🧸 softies</a><nav class="navlinks" id="mainNav"><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="about.html">About</a></nav><div class="navicons"><a class="icon-btn" href="shop.html" aria-label="Search">⌕</a><a class="icon-btn" href="wishlist.html" aria-label="Wishlist">♡<span class="count" data-wishlist-count>0</span></a><a class="icon-btn" href="cart.html" aria-label="Cart">🛒<span class="count" data-cart-count>0</span></a><button class="icon-btn menu-btn" id="mobileMenuBtn" aria-label="Open menu" onclick="toggleMobileMenu()">☰</button></div></div></header>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><div class="logo">🧸 softies</div><p>Make Every Moment More Magical. Safe, fun and creative toys for every little dreamer.</p></div><div><b>Quick Links</b><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="cart.html">Cart</a><a href="wishlist.html">Wishlist</a></div><div><b>Categories</b><a href="shop.html?category=Educational">Educational</a><a href="shop.html?category=Soft%20Toys">Soft Toys</a><a href="shop.html?category=Outdoor%20Toys">Outdoor Toys</a></div><div><b>Customer Service</b><a href="order-success.html">Track Order</a><a href="#">Privacy Policy</a><a href="#">Terms & Conditions</a><a href="#">Return Policy</a></div></div><div class="container copyright">© 2026 softies. All rights reserved. Demo mode uses localStorage.</div></footer>`}
document.addEventListener("DOMContentLoaded",()=>{let h=$("#site-header"),f=$("#site-footer");if(h)h.innerHTML=header();if(f)f.innerHTML=footer();updateCounts()});
function toggleMobileMenu(){
  const nav=document.querySelector("#mainNav");
  if(nav) nav.classList.toggle("mobile-open");
}
