const products = [
  {
    "id": 1,
    "name": "Colorful Learning Blocks",
    "category": "Educational",
    "price": 372,
    "oldPrice": 522,
    "discount": 29,
    "rating": 4.1,
    "reviews": 27,
    "image": "https://swakum.com/cdn/shop/files/House_Building_Blocks_Set_72_Pieces_Creative_Construction_Toy_for_Kids_Age_3_1.png?v=1783309972&width=1780",
    "description": "Colorful Learning Blocks is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 8,
    "sku": "TL-EDU-001",
    "tags": [
      "educational",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": false
  },
  {
    "id": 2,
    "name": "Alphabet Learning Board",
    "category": "Educational",
    "price": 445,
    "oldPrice": 645,
    "discount": 31,
    "rating": 4.2,
    "reviews": 34,
    "image": "https://nextgentoys.in/cdn/shop/files/ChatGPTImageFeb9_2026_06_07_26PM.png?v=1770640876&width=3840",
    "description": "Alphabet Learning Board is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 11,
    "sku": "TL-EDU-002",
    "tags": [
      "educational",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": false
  },
  {
    "id": 3,
    "name": "Science Experiment Kit",
    "category": "Educational",
    "price": 518,
    "oldPrice": 768,
    "discount": 33,
    "rating": 4.3,
    "reviews": 41,
    "image": "https://m.media-amazon.com/images/I/81WIgNnQCrL._AC_SL3840_.jpg",
    "description": "Science Experiment Kit is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 14,
    "sku": "TL-EDU-003",
    "tags": [
      "educational",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": false
  },
  {
    "id": 4,
    "name": "Cuddly Teddy Bear",
    "category": "Soft Toys",
    "price": 591,
    "oldPrice": 691,
    "discount": 14,
    "rating": 4.4,
    "reviews": 48,
    "image": "https://i5.walmartimages.com/asr/2fd3f2c7-e5be-4d0d-90aa-8d1f0e133156.7fe07062e48ec14718c819bf2571652c.jpeg?odnBg=FFFFFF&odnHeight=576&odnWidth=576",
    "description": "Cuddly Teddy Bear is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 17,
    "sku": "TL-SOF-004",
    "tags": [
      "soft-toys",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": true
  },
  {
    "id": 5,
    "name": "Rainbow Unicorn Plush",
    "category": "Soft Toys",
    "price": 664,
    "oldPrice": 814,
    "discount": 18,
    "rating": 4.5,
    "reviews": 55,
    "image": "https://www.kroger.com/product/images/medium/front/0005958437657",
    "description": "Rainbow Unicorn Plush is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 20,
    "sku": "TL-SOF-005",
    "tags": [
      "soft-toys",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": false
  },
  {
    "id": 6,
    "name": "Sleepy Panda Soft Toy",
    "category": "Soft Toys",
    "price": 737,
    "oldPrice": 937,
    "discount": 21,
    "rating": 4.6,
    "reviews": 62,
    "image": "https://cdn.shopify.com/s/files/1/0566/8444/5755/files/Kawaii-Bamboo-Panda-Plush-Toy-10_480x480.jpg?v=1705214756",
    "description": "Sleepy Panda Soft Toy is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 23,
    "sku": "TL-SOF-006",
    "tags": [
      "soft-toys",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": false
  },
  {
    "id": 7,
    "name": "RC Racing Car",
    "category": "Remote Control",
    "price": 810,
    "oldPrice": 1060,
    "discount": 24,
    "rating": 4.7,
    "reviews": 69,
    "image": "https://deodap.in/cdn/shop/files/WhatsApp_Image_2026-08-25_at_5.27.07_PM_40656af1-147a-40d6-a07c-877fe6f00731.jpg?v=1787750217&width=1946",
    "description": "RC Racing Car is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 26,
    "sku": "TL-REM-007",
    "tags": [
      "remote-control",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": false
  },
  {
    "id": 8,
    "name": "Remote Control Monster Truck",
    "category": "Remote Control",
    "price": 883,
    "oldPrice": 983,
    "discount": 10,
    "rating": 4.8,
    "reviews": 76,
    "image": "https://m.media-amazon.com/images/I/81TvmOmtjML._AC_SL1500_.jpg",
    "description": "Remote Control Monster Truck is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 29,
    "sku": "TL-REM-008",
    "tags": [
      "remote-control",
      "kids",
      "toy"
    ],
    "featured": true,
    "bestSeller": true
  },
  {
    "id": 9,
    "name": "RC Stunt Robot",
    "category": "Remote Control",
    "price": 956,
    "oldPrice": 1106,
    "discount": 14,
    "rating": 4.9,
    "reviews": 83,
    "image": "https://cocolandtoys.com/cdn/shop/files/H4c3c96c42bc84def8dbad4894897f4ae1.jpg?v=1772962059&width=2400",
    "description": "RC Stunt Robot is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 32,
    "sku": "TL-REM-009",
    "tags": [
      "remote-control",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 10,
    "name": "Kids Cricket Set",
    "category": "Outdoor Toys",
    "price": 1029,
    "oldPrice": 1229,
    "discount": 16,
    "rating": 4.0,
    "reviews": 90,
    "image": "https://i.ebayimg.com/images/g/wA8AAOSw1-Fnq~rl/s-l1200.jpg",
    "description": "Kids Cricket Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 5,
    "sku": "TL-OUT-010",
    "tags": [
      "outdoor-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 11,
    "name": "Bubble Blaster",
    "category": "Outdoor Toys",
    "price": 1102,
    "oldPrice": 1352,
    "discount": 18,
    "rating": 4.1,
    "reviews": 97,
    "image": "https://www.jiomart.com/images/product/original/rvn4z5vp93/hamleys-plastic-bubble-blaster-with-fuel-impulse-3-y-and-above-product-images-orvn4z5vp93-p600061964-1-202304011218.jpg?im=Resize%3D%28420%2C420%29",
    "description": "Bubble Blaster is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 8,
    "sku": "TL-OUT-011",
    "tags": [
      "outdoor-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 12,
    "name": "Junior Basketball Set",
    "category": "Outdoor Toys",
    "price": 1175,
    "oldPrice": 1275,
    "discount": 8,
    "rating": 4.2,
    "reviews": 104,
    "image": "https://http2.mlstatic.com/D_NQ_NP_741003-MLA82649815749_022025-O.webp",
    "description": "Junior Basketball Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 11,
    "sku": "TL-OUT-012",
    "tags": [
      "outdoor-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": true
  },
  {
    "id": 13,
    "name": "Creative Building Bricks",
    "category": "Building Toys",
    "price": 1248,
    "oldPrice": 1398,
    "discount": 11,
    "rating": 4.3,
    "reviews": 111,
    "image": "https://swakum.com/cdn/shop/files/House_Building_Blocks_Set_72_Pieces_Creative_Construction_Toy_for_Kids_Age_3_1.png?v=1783309972&width=1780",
    "description": "Creative Building Bricks is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 14,
    "sku": "TL-BUI-013",
    "tags": [
      "building-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 14,
    "name": "Magnetic Tile Set",
    "category": "Building Toys",
    "price": 321,
    "oldPrice": 521,
    "discount": 38,
    "rating": 4.4,
    "reviews": 118,
    "image": "https://swakum.com/cdn/shop/files/House_Building_Blocks_Set_72_Pieces_Creative_Construction_Toy_for_Kids_Age_3_1.png?v=1783309972&width=1780",
    "description": "Magnetic Tile Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 17,
    "sku": "TL-BUI-014",
    "tags": [
      "building-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 15,
    "name": "Mini Construction Set",
    "category": "Building Toys",
    "price": 394,
    "oldPrice": 644,
    "discount": 39,
    "rating": 4.5,
    "reviews": 125,
    "image": "https://swakum.com/cdn/shop/files/House_Building_Blocks_Set_72_Pieces_Creative_Construction_Toy_for_Kids_Age_3_1.png?v=1783309972&width=1780",
    "description": "Mini Construction Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 20,
    "sku": "TL-BUI-015",
    "tags": [
      "building-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 16,
    "name": "Musical Baby Piano",
    "category": "Baby Toys",
    "price": 467,
    "oldPrice": 567,
    "discount": 18,
    "rating": 4.6,
    "reviews": 132,
    "image": "https://assets.costway.com/media/catalog/product/cache/0/thumbnail/80x/9df78eab33525d08d6e5fb8d27136e95/t/TM10060DK/31_Keys_Kids_Piano_Keyboard_size-4.jpg",
    "description": "Musical Baby Piano is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 23,
    "sku": "TL-BAB-016",
    "tags": [
      "baby-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": true
  },
  {
    "id": 17,
    "name": "Baby Activity Cube",
    "category": "Baby Toys",
    "price": 540,
    "oldPrice": 690,
    "discount": 22,
    "rating": 4.7,
    "reviews": 139,
    "image": "https://i5.walmartimages.com/seo/LeapFrog-Touch-Learn-Wooden-Activity-Cube-FSC-100-Plastic-Wood-100-FSC-Certified-Wood-Baby-and-Toddler-Toys_d2bf17e3-00c9-4144-baad-29b4566ca526.f209888e428e3bfd09b3c4a7a933adc1.jpeg?odnBg=FFFFFF&odnHeight=117&odnWidth=117",
    "description": "Baby Activity Cube is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 26,
    "sku": "TL-BAB-017",
    "tags": [
      "baby-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 18,
    "name": "Soft Rattle Set",
    "category": "Baby Toys",
    "price": 613,
    "oldPrice": 813,
    "discount": 25,
    "rating": 4.8,
    "reviews": 146,
    "image": "https://assets.myntassets.com/assets/images/27226758/2024/1/27/ad4d1310-74ef-4915-9d83-79e9c781ad5e1706344583186ADKDBabyRattleSetforNewBornBabiesPackof4-Multicolor2.jpg",
    "description": "Soft Rattle Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 29,
    "sku": "TL-BAB-018",
    "tags": [
      "baby-toys",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 19,
    "name": "Family Adventure Board Game",
    "category": "Board Games",
    "price": 686,
    "oldPrice": 936,
    "discount": 27,
    "rating": 4.9,
    "reviews": 153,
    "image": "https://i5.walmartimages.com/asr/ffa4b4b1-79a1-4da3-a3e7-8cf8adafaca7_1.eb4ab1fcbf423142bf60d648496a3b60.jpeg?odnBg=ffffff&odnHeight=450&odnWidth=450",
    "description": "Family Adventure Board Game is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 32,
    "sku": "TL-BOA-019",
    "tags": [
      "board-games",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 20,
    "name": "Kids Chess Set",
    "category": "Board Games",
    "price": 759,
    "oldPrice": 859,
    "discount": 12,
    "rating": 4.0,
    "reviews": 160,
    "image": "https://i5.walmartimages.com/asr/ffa4b4b1-79a1-4da3-a3e7-8cf8adafaca7_1.eb4ab1fcbf423142bf60d648496a3b60.jpeg?odnBg=ffffff&odnHeight=450&odnWidth=450",
    "description": "Kids Chess Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 5,
    "sku": "TL-BOA-020",
    "tags": [
      "board-games",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": true
  },
  {
    "id": 21,
    "name": "Memory Match Game",
    "category": "Board Games",
    "price": 832,
    "oldPrice": 982,
    "discount": 15,
    "rating": 4.1,
    "reviews": 167,
    "image": "https://i5.walmartimages.com/asr/ffa4b4b1-79a1-4da3-a3e7-8cf8adafaca7_1.eb4ab1fcbf423142bf60d648496a3b60.jpeg?odnBg=ffffff&odnHeight=450&odnWidth=450",
    "description": "Memory Match Game is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 8,
    "sku": "TL-BOA-021",
    "tags": [
      "board-games",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 22,
    "name": "City Fire Engine",
    "category": "Vehicles",
    "price": 905,
    "oldPrice": 1105,
    "discount": 18,
    "rating": 4.2,
    "reviews": 174,
    "image": "https://igrashky24.com.ua/image/catalog/categori/ihrashky.png",
    "description": "City Fire Engine is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 11,
    "sku": "TL-VEH-022",
    "tags": [
      "vehicles",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 23,
    "name": "Die-Cast Sports Car",
    "category": "Vehicles",
    "price": 978,
    "oldPrice": 1228,
    "discount": 20,
    "rating": 4.3,
    "reviews": 181,
    "image": "https://deodap.in/cdn/shop/files/WhatsApp_Image_2026-08-25_at_5.27.07_PM_40656af1-147a-40d6-a07c-877fe6f00731.jpg?v=1787750217&width=1946",
    "description": "Die-Cast Sports Car is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 14,
    "sku": "TL-VEH-023",
    "tags": [
      "vehicles",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 24,
    "name": "Wooden Train Set",
    "category": "Vehicles",
    "price": 1051,
    "oldPrice": 1151,
    "discount": 9,
    "rating": 4.4,
    "reviews": 188,
    "image": "https://i.ebayimg.com/images/g/B84AAOSw3vhkt3sf/s-l1200.jpg",
    "description": "Wooden Train Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 17,
    "sku": "TL-VEH-024",
    "tags": [
      "vehicles",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": true
  },
  {
    "id": 25,
    "name": "Fashion Doll Set",
    "category": "Dolls",
    "price": 1124,
    "oldPrice": 1274,
    "discount": 12,
    "rating": 4.5,
    "reviews": 195,
    "image": "https://toysatfoys.com/cdn/shop/files/Toys_At_Foys_Barbie_Figure_Skater_Fashion_Doll1.jpg?v=1740671159&width=1200",
    "description": "Fashion Doll Set is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 20,
    "sku": "TL-DOL-025",
    "tags": [
      "dolls",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 26,
    "name": "Princess Doll House",
    "category": "Dolls",
    "price": 1197,
    "oldPrice": 1397,
    "discount": 14,
    "rating": 4.6,
    "reviews": 202,
    "image": "https://swakum.com/cdn/shop/files/House_Building_Blocks_Set_72_Pieces_Creative_Construction_Toy_for_Kids_Age_3_1.png?v=1783309972&width=1780",
    "description": "Princess Doll House is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 23,
    "sku": "TL-DOL-026",
    "tags": [
      "dolls",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 27,
    "name": "Baby Doll Care Kit",
    "category": "Dolls",
    "price": 1270,
    "oldPrice": 1520,
    "discount": 16,
    "rating": 4.7,
    "reviews": 209,
    "image": "https://i5.walmartimages.com/asr/2fd3f2c7-e5be-4d0d-90aa-8d1f0e133156.7fe07062e48ec14718c819bf2571652c.jpeg?odnBg=FFFFFF&odnHeight=576&odnWidth=576",
    "description": "Baby Doll Care Kit is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 26,
    "sku": "TL-DOL-027",
    "tags": [
      "dolls",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 28,
    "name": "Superhero Action Figure",
    "category": "Action Figures",
    "price": 343,
    "oldPrice": 443,
    "discount": 23,
    "rating": 4.8,
    "reviews": 216,
    "image": "https://cocolandtoys.com/cdn/shop/files/H4c3c96c42bc84def8dbad4894897f4ae1.jpg?v=1772962059&width=2400",
    "description": "Superhero Action Figure is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 29,
    "sku": "TL-ACT-028",
    "tags": [
      "action-figures",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": true
  },
  {
    "id": 29,
    "name": "Space Explorer Figure",
    "category": "Action Figures",
    "price": 416,
    "oldPrice": 566,
    "discount": 27,
    "rating": 4.9,
    "reviews": 223,
    "image": "https://igrashky24.com.ua/image/catalog/categori/ihrashky.png",
    "description": "Space Explorer Figure is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "3-6 Years",
    "brand": "softies",
    "stock": 32,
    "sku": "TL-ACT-029",
    "tags": [
      "action-figures",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  },
  {
    "id": 30,
    "name": "Dinosaur Adventure Figure",
    "category": "Action Figures",
    "price": 489,
    "oldPrice": 689,
    "discount": 29,
    "rating": 4.0,
    "reviews": 230,
    "image": "https://m.media-amazon.com/images/I/8163QHb0DPL._AC_SL1500_.jpg",
    "description": "Dinosaur Adventure Figure is designed for safe, engaging and joyful play, helping children explore, imagine and learn.",
    "age": "6-10 Years",
    "brand": "softies",
    "stock": 5,
    "sku": "TL-ACT-030",
    "tags": [
      "action-figures",
      "kids",
      "toy"
    ],
    "featured": false,
    "bestSeller": false
  }
];
